theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false

# [editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
# Use system clipboard
# y = "yank_main_selection_to_clipboard"
# p = "paste_clipboard_before"
"}" = "goto_next_paragraph"   # next empty line / paragraph
"{" = "goto_prev_paragraph"   # previous empty line / paragraph

[keys.insert]
j = { k = "normal_mode" }
