[[language]]
name = "typescript"
shebangs = ["deno"]
roots = ["deno.json", "deno.jsonc"]
file-types = ["js", "ts", "jsx", "tsx"]
language-servers = ["deno-lsp", "tailwindcss-ls"]
auto-format = true

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.gopls.config]
"formatting.gofumpt" = true

[language-server.rust-analyzer.config.check]
command = "clippy"
[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }
auto-format = true

[[language]]
name = "typescript"
auto-format = true
# formatter = { command = 'prettier', args = ["--parser", "typescript"] }
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
# config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true }}

[[language]]
name = "tsx"
# formatter = { command = 'prettier', args = ["--parser", "typescript"] }
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "javascript"] }
auto-format = true
